### ISSUE TITLE
any chance to update to 0.10?

### ISSUE THREAD

**Issue by moebiussurfing** [JoshuaBatty/ofxNodeGraph#2]
I am looking for a very tiny patching system from params source to targets... not user if you recommends the addon for this... or another one

**Comment by JoshuaBatty** [comment]
Hey @moebiussurfing i stopped pursuing this. If you want a node patching UI environment for oF then i'd highly recommend checking out ofxOceanode by PlayModes. https://github.com/PlaymodesStudio/ofxOceanode
